jobs:
  - name: apply
    max_in_flight: 1
    plan:
      - get: aws-b-accounts-config
        passed:
          - plan
        trigger: false
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TFSTATE: ((aws.tfstate))
          TFLOCKS: ((aws.tflocks))
          S3_BUCKET_NAME: ((aws.s3_bucket))
          GIT_PAT: ((github_pat))
