// Add in any variables you which to export or be made available from your terraform here.

//Example of exporting a non sensitive value
output "string" {
  value = random_pet.name.id
  description = "The ID of a random pet name created by terraform"
}

//Example of exporting a sensitive value
output "some-password" {
  value     = random_password.some_password.result
  sensitive = true
  description = "A password which is generated by terraform"
}
