---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: trufflesecurity/trufflehog
    tag: latest
inputs:
  - name: pull-request
run:
  path: ./pull-request/ci/tasks/trufflehog/task.sh
