---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: latest
inputs:
  - name: repo-git
run:
  path: sh
  args: ["./ci/tasks/terraform/terraform-apply.sh"]
  dir: repo-git
