---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: latest
inputs:
  - name: pull-request
outputs:
  - name: terraform-output
run:
  path: sh
  args: ["./ci/tasks/terraform/terraform-plan.sh"]
  dir: pull-request
