---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: bridgecrew/checkov
    tag: latest
inputs:
  - name: pull-request
  - name: terraform-output
run:
  path: ./pull-request/ci/tasks/checkov/task.sh
