---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: aquasec/tfsec
    tag: latest
inputs:
  - name: pull-request
run:
  path: ./pull-request/ci/tasks/tfsec/task.sh
